#!/bin/sh

# Do nothing if interrupted
trap '' INT TSTP

userresources=$HOME/.config/x11/Xresources
#usermodmap=$HOME/.config/x11/Xmodmap

# merge in defaults
[ -f "$userresources" ] && xrdb -merge "$userresources"
#[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# Restore backlight
brillo -I

# X settings
xset +fp ~/.local/share/fonts/misc,/usr/share/fonts/misc,/usr/share/fonts/X11/spleen
xset dpms 300 #Blank screen after 5 minutes (same time as lock kicks in)
xinput disable "Elan Touchpad"
hsetroot -solid '#1c1c1c'

# "Login manager"
lock &
sleep 0.5
pgrep -x xsecurelock >/dev/null 2>&1 && pkill -x -USR2 xsecurelock # To show password prompt immediately
# Begin session
exec dbus-run-session -- herbstluftwm
