#!/bin/sh

# Create fifo
if [ ! -p /tmp/new_notifs ]; then
    [ -e /tmp/new_notifs ] && rm /tmp/new_notifs
    mkfifo /tmp/new_notifs
fi

exec tiramisu -o "#summary\t#body\t#timeout\t#id" |
    while read -r line; do
        echo "$line" >/tmp/new_notifs
        echo "LOG $line" >>/tmp/notif_log
    done
